apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    name: mongo
  name: mongodata
  namespace: todo-app 
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "gp2"
  resources:
    requests:
      storage: 100Mi
status: {}