apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    name: todos
  namespace: todo-app
spec:
  # type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    name: todos
