apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    name: todos
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: todos
